import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The sidebar is written out by hand rather than autogenerated so that reading
// order is a deliberate choice: what this is, how to run it, how it works, then
// the reference material you come back for.
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'quickstart',
    {
      type: 'category',
      label: 'Background',
      collapsed: false,
      items: ['background/vercel', 'background/jamstack', 'background/docusaurus', 'background/age'],
    },
    'architecture',
    'exposers',
    'local-platform',
    {
      type: 'category',
      label: 'Runbooks',
      collapsed: false,
      items: ['runbooks/github-app', 'runbooks/zrok2', 'runbooks/frontdoor'],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        'reference/configuration',
        'reference/repo-config',
        'reference/cli',
        'reference/build-logs',
        'reference/security',
      ],
    },
    'troubleshooting',
    {
      type: 'category',
      label: 'Future',
      collapsed: false,
      items: ['future/ziti-native-previews'],
    },
  ],
};

export default sidebars;
